// This file was autogenerated by tools/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../src/sage/core.js', ['sage.core'], []);
goog.addDependency('../src/sage/engines/kernel.js', ['sage.engines.kernel'], ['sage.core', 'sage.types.process', 'sage.utilities.pool', 'sage.utilities.time']);
goog.addDependency('../src/sage/engines/world.js', ['sage.engines.world'], ['sage.core', 'sage.types.entity', 'sage.types.process', 'sage.utilities.pool']);
goog.addDependency('../src/sage/sage.js', ['sage.sage'], ['sage.core', 'sage.engines.kernel', 'sage.engines.world']);
goog.addDependency('../src/sage/types/entity.js', ['sage.types.entity'], ['sage.core']);
goog.addDependency('../src/sage/types/process.js', ['sage.types.process'], ['sage.core']);
goog.addDependency('../src/sage/utilities/pool.js', ['sage.utilities.pool'], ['sage.core']);
goog.addDependency('../src/sage/utilities/time.js', ['sage.utilities.time'], ['sage.core']);
