var sage={sage:{}},sage=function(){var b={version:"0.2.9",type:{},initialize:function(a){a=a||{};sage.time.initialize(a.time);sage.pool.initialize(a.pool);sage.world.initialize(a.db);sage.kernel.initialize(a.kernel);return b}};return b}();sage.utilities={};sage.utilities.time={};
sage.time=function(){var b={start:0,delta:0,now:0},a={now:0},c={initialize:function(){c.real=b;c.game=a;return this},now:function(){return a.now},delta:function(){return b.delta},convertTimedProcessFormat:function(a){var d=void 0===profiles.units?"ms":profiles.units,c="ms"===d?1:"s"===d?1E3:"min"===d?6E4:0;a.repeat=void 0===a.repeat?-1:a.repeat;a.frequency=void 0===a.frequency?1:a.frequency;a.offset=void 0===a.offset?0:a.offset;"game"!==d&&(a.offset*=c,a.frequency*=c);a.lastUpdate=Date.now();return a},
isProcessReadyToFire:function(c){var d=c.timed;if(("game"===units?a.now:b.now)-d.lastUpdate>=d.frequency)0<d.repeat?d.repeat-=1:0===d.repeat&&c.remove();return!0}};return c}();sage.utilities.pool={};sage.pool=function(){var b={},a;b.initialize=function(){a={};return this};b.claim=function(c,b,d){return(c=a[c])&&0<c.length?c.pop():new b(d)};b.yield=function(c,b){var d=a[c];void 0===d&&(d=a[c]=[]);d.push(b);return this};return b}();sage.types={};
sage.types.process=function(){var b={},a=function(){this.qid=this.cid=this.eid=this.pkid=0;this.component=this.entity=void 0;this.on=!0};a.prototype=new function(){this.fn=this;this.kill=function(){sage.kill(this.entity);return this};this.exclude=function(){sage.exclude(this);return this};this.play=function(){this.on=!0;return this};this.pause=this.stop=function(){this.on=!1;return this};this.update=function(){return this.entity.on&&this.on?(this.component.update.call(this.entity),!0):!1};this.startup=
function(a){a=void 0!==a?a:b;this.component.startup&&this.component.startup.call(this.entity,a)};this.shutdown=function(){this.component.shutdown&&this.component.shutdown.call(this.entity)}};return a}();sage.engines={};sage.engines.kernel={};
sage.kernel=function(){var b,a={},c,e={updatesPerSecond:2,workPerSecond:100,on:!0},d=[],j=[],g=[],k=0,n=0,l=0,y=function(){if(!1===b.on)return w(),!1;u=c.real.now=Date.now();console.log("update: "+c.real.now);for(var a=d,h=0,i=k,e,f=sage.time;h<i;h++)e=a[h],f.processTimeReadyToFire(e)&&e.update();a=v;h=l;i=d;f=e=i.length;if(0!==e){for(;a--;){i[h].update();h+=1;h>=e&&(c.game.now+=1,h=k);f-=1;if(0>=f)break;p=Date.now();q=p-u;if(q>0.75*r)break}l=h}a=void 0;h=g;a=d;i=0;for(e=h.length;i<e;i++)f=h[i],f.qid&&
(void 0!==f.timed&&(s(f,a[k-1]),k-=1),s(f,a[a.length-1]),a.length-=1,delete f.qid);g.length=0;a=j;h=d;i=0;for(e=a.length;i<e;i++)f=a[i],f.component.update&&(f.qid=h.length,h[f.qid]=f,void 0!==f.timed&&(s(f,h[k]),k+=1));j.length=0;c.real.delta=q;return!0},r,v,u,p,q,t,m={},s=function(a,b){var c;c=b.qid;d[a.qid]=b;b.qid=a.qid;d[c]=a;a.qid=c};m.start=function(){r=1E3/b.updatesPerSecond;p=c.real.start=Date.now();v=b.workPerSecond;clearInterval(t);t=setInterval(y,r)};var w=m.stop=function(){clearInterval(t)};
a.initialize=function(x){c=sage.time;d=[];j=[];g=[];l=n=k=0;b=_.extend({},e);a.settings(x);return b};a.settings=function(a){a&&(b=_.extend(b,a));return b};a.on=function(a){b.on=void 0!==a?a:b.on;return b.on};a.start=a.play=function(){l=n;b.on=!0;m.start()};a.pause=function(){n=l;b.on=!1;m.stop()};a.stop=function(){n=0;b.on=!1;m.stop()};a.add=function(a){if(void 0===a.component.update&&void 0===a.component.tick)return!1;j.push(a);return!0};a.remove=function(a){a=void 0!==a.pkid?a:d[a];g.push(a);return a};
return a}();sage.types.entity=function(){var b=function(){this.pkid=0;this.on=!0};b.prototype=new function(){this.fn=this;this.clone=function(a){var b=this.spawn(),a=a||{};sage.world.processes({eid:this.pkid}).each(function(e){sage.include(b,e.cid,a[e.cid])});return b};this.spawn=function(a){return sage.entity(a)};this.kill=function(){sage.kill(this);return this};this.getComponent=function(a){return sage.query.getComponent(a)};this.getProcess=function(a){return sage.query.getProcess(this.pkid,a)};this.include=
this.require=function(a,b){sage.include(this,a,b);return this};this.includeMany=function(a){sage.includeMany(this,a);return this};this.exclude=function(a){a=sage.world.processes({eid:this.pkid,cid:a}).first();sage.exclude(a);return this};this.excludeMany=function(a){sage.excludeMany(this,a);return this};this.restart=this.enable=function(){sage.world.processes({eid:this.pkid}).each(function(a){a.component.startup&&a.component.startup.call(a)});this.on=!0;return this};this.suspend=this.disable=function(){sage.world.processes({eid:this.pkid}).each(function(a){a.component.shutdown&&
a.component.shutdown.call(a)});this.on=!1;return this}};return b}();sage.engines.world={};
sage.world=function(){var b,a,c,e={initialize:function(d){c={nextEntityID:0,nextProcessID:0};e.entities=TAFFY();e.components=TAFFY();e.processes=TAFFY();db=e;b=sage.types.entity;a=sage.types.process;c=_.extend(c,d);return this}};sage.query={getComponent:function(a){return e.components({pkid:a}).first()},getProcess:function(a,b){return e.processes({eid:a,cid:b}).first()}};sage.entity=sage.spawn=function(a){var j=sage.pool.claim("Entity",b);j.pkid=c.nextEntityID;c.nextEntityID=j.pkid+1;db.entities.insert(j);
a&&sage.includeMany(j,a);return j};sage.kill=function(a){db.entities({pkid:a.pkid}).remove();sage.pool.yield("Entity",a);db.processes({eid:a.pkid}).each(function(a){sage.exclude(a)});return this};sage.include=function(a,b,c){a=sage.process(a,b);if(!a)return a;a.startup(c);return this};sage.includeMany=function(a,b){_.forEach(b,function(b,c){sage.include(a,c,b)});return this};sage.exclude=function(a){db.processes({pkid:a.pkid}).remove();sage.pool.yield("Process",a);sage.kernel.remove(a.qid);a.shutdown();
return this};sage.excludeMany=function(a,b){_.forEach(b,function(b){sage.exclude(a,b)});return this};sage.component=function(a,b){if(db.components({cid:a}).first())return this;b.pkid=a;db.components.insert(b);return this};sage.process=function(b,e){var g=!1;if(db.processes({eid:b.pkid,cid:e}).first())return g;g=sage.pool.claim("Process",a);g.pkid=c.nextProcessID;g.eid=b.pkid;g.cid=e;g.entity=b;g.component=db.components({pkid:e}).first();g.qid=sage.kernel.add(g);c.nextProcessID=g.pkid+1;db.processes.insert(g);
return g};return e}();sage.library={};

/* Sage version 0.1.0 in utf-8 */