// This file was autogenerated by tools/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../src/sage/engines/kernel.js', ['sage.engines.kernel', 'sage.utilities.time'], ['sage.sage', 'sage.types.process', 'sage.utilities.pool']);
goog.addDependency('../src/sage/engines/world.js', ['sage.engines.world'], ['sage.engines.kernel', 'sage.sage', 'sage.types.entity', 'sage.types.process', 'sage.utilities.pool']);
goog.addDependency('../src/sage/library.js', ['sage.library'], ['sage.engines.kernel', 'sage.engines.world', 'sage.sage']);
goog.addDependency('../src/sage/sage.js', ['sage.sage'], []);
goog.addDependency('../src/sage/types/entity.js', ['sage.types.entity'], ['sage.sage']);
goog.addDependency('../src/sage/types/process.js', ['sage.types.process'], ['sage.sage']);
goog.addDependency('../src/sage/utilities/pool.js', ['sage.utilities.pool'], ['sage.sage']);
goog.addDependency('../src/sage/utilities/query.js', ['sage.utilities.query'], ['sage.engines.world', 'sage.sage', 'sage.types.entity', 'sage.types.process']);
goog.addDependency('../src/sage/utilities/time.js', ['sage.utilities.time'], ['sage.sage']);
